# Generated by Django 4.2.28 on 2026-02-16 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='post',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='post',
            name='priority',
            field=models.DecimalField(decimal_places=2, help_text='Lower number = higher authority (e.g., 1.00 for Secretary, 4.01 for Admin Manager)', max_digits=5),
        ),
    ]
