# Generated by Django 4.2.28 on 2026-02-21 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_userloginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(help_text='e.g., 25-26', max_length=10)),
                ('last_no', models.PositiveIntegerField(default=0)),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Voucher Number',
                'verbose_name_plural': 'Voucher Numbers',
                'db_table': 'voucher_number',
            },
        ),
    ]
