# Generated by Django 4.2.28 on 2026-02-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_vouchernumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentpriority',
            options={'ordering': ['level', 'name'], 'verbose_name_plural': 'Document Priorities'},
        ),
        migrations.AddField(
            model_name='documentpriority',
            name='level',
            field=models.IntegerField(default=10, help_text='Priority level (lower = more urgent)'),
        ),
    ]
