# Generated by Django 4.2.28 on 2026-03-19 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_documentpriority_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchernumber',
            name='financial_year',
        ),
        migrations.RemoveField(
            model_name='vouchernumber',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='vouchernumber',
            name='to_date',
        ),
        migrations.AddField(
            model_name='vouchernumber',
            name='year',
            field=models.CharField(default='2026', help_text='e.g., 2026', max_length=4),
            preserve_default=False,
        ),
    ]
