# Generated by Django 4.2.28 on 2026-02-11 04:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('subject', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_files', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_files', to=settings.AUTH_USER_MODEL)),
                ('current_holder', models.ForeignKey(help_text='Post currently holding this file', on_delete=django.db.models.deletion.PROTECT, related_name='current_files', to='administration.post')),
                ('current_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='files', to='administration.documentstatus')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='administration.department')),
                ('document_origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='administration.documentorigin')),
                ('document_priority', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='administration.documentpriority')),
                ('document_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='files', to='administration.documenttype')),
            ],
            options={
                'db_table': 'file_master',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_required', models.BooleanField(default=True, help_text='True if action required, False for view-only')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('moved_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='filetracking.filemaster')),
                ('from_post', models.ForeignKey(blank=True, help_text='Sender post (null for initial creation)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_files', to='administration.post')),
                ('moved_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_movements', to=settings.AUTH_USER_MODEL)),
                ('to_post', models.ForeignKey(help_text='Receiver post', on_delete=django.db.models.deletion.PROTECT, related_name='received_files', to='administration.post')),
            ],
            options={
                'db_table': 'file_movement',
                'ordering': ['moved_at'],
            },
        ),
        migrations.CreateModel(
            name='FileDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='file_documents/%Y/%m/')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='filetracking.filemaster')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'file_document',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RETURN', 'Return for Clarification'), ('FORWARD', 'Forward')], max_length=20)),
                ('remarks', models.TextField(help_text='Required remarks for the action')),
                ('action_at', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='file_actions', to=settings.AUTH_USER_MODEL)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='filetracking.filemaster')),
                ('post', models.ForeignKey(help_text='Post that took this action', on_delete=django.db.models.deletion.PROTECT, related_name='file_actions', to='administration.post')),
            ],
            options={
                'db_table': 'file_action',
                'ordering': ['action_at'],
            },
        ),
    ]
