# Generated by Django 4.2.28 on 2026-02-14 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administration', '0001_initial'),
        ('filetracking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='filetracking.filemaster')),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shared_files_by', to=settings.AUTH_USER_MODEL)),
                ('shared_with', models.ForeignKey(help_text='Post that has view access', on_delete=django.db.models.deletion.PROTECT, related_name='shared_files', to='administration.post')),
            ],
            options={
                'db_table': 'file_share',
                'ordering': ['-created_at'],
                'unique_together': {('file', 'shared_with')},
            },
        ),
    ]
