# Generated by Django 4.2.28 on 2026-02-20 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filetracking', '0002_fileshare'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemaster',
            name='current_user',
            field=models.ForeignKey(blank=True, help_text='Specific user holding this file (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='held_files', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filemovement',
            name='to_user',
            field=models.ForeignKey(blank=True, help_text='Specific receiver user (if applicable)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_file_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fileaction',
            name='action_type',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RETURN', 'Return for Clarification'), ('FORWARD', 'Forward'), ('CLOSE', 'Close File')], max_length=20),
        ),
    ]
