# Generated by Django 4.2.28 on 2026-02-21 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0003_filemaster_current_user_filemovement_to_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemovement',
            name='is_return',
            field=models.BooleanField(default=False, help_text='True if this movement is a return action'),
        ),
    ]
