# Generated by Django 4.2.28 on 2026-02-28 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filetracking', '0004_filemovement_is_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemaster',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='filemaster',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_files_master', to=settings.AUTH_USER_MODEL),
        ),
    ]
