# Generated by Django 4.2.28 on 2026-02-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0005_filemaster_approved_at_filemaster_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileaction',
            name='view_by_id',
            field=models.CharField(blank=True, help_text='Comma-separated IDs of posts assigned to view this file during this action', max_length=255, null=True),
        ),
    ]
