# Generated by Django 4.2.28 on 2026-03-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0006_fileaction_view_by_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemovement',
            name='is_recalled',
            field=models.BooleanField(default=False, help_text='True if this forward was recalled by the sender'),
        ),
        migrations.AlterField(
            model_name='fileaction',
            name='action_type',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RETURN', 'Return for Clarification'), ('FORWARD', 'Forward'), ('CLOSE', 'Close File'), ('RECALL', 'Recall Forwarded File')], max_length=20),
        ),
    ]
