# Generated by Django 4.2.28 on 2026-03-18 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0007_filemovement_is_recalled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filedocument',
            name='document',
        ),
        migrations.AddField(
            model_name='filedocument',
            name='action',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_documents', to='filetracking.fileaction'),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='content',
            field=models.BinaryField(null=True),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='filedocument',
            name='mimetype',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
