# Generated by Django 4.2.28 on 2026-03-19 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_alter_documentpriority_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filetracking', '0008_remove_filedocument_document_filedocument_action_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fileshare',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='shared_with_user',
            field=models.ForeignKey(blank=True, help_text='Specific user who has view access', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shared_files_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fileshare',
            unique_together={('file', 'shared_with', 'shared_with_user')},
        ),
    ]
