# Generated by Django 4.2.28 on 2026-03-28 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0009_alter_fileshare_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileshare',
            name='is_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fileshare',
            name='viewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
