# Generated by Django 4.2.28 on 2026-07-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0010_fileshare_is_viewed_fileshare_viewed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileaction',
            name='action_type',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RETURN', 'Return for Clarification'), ('FORWARD', 'Forward'), ('CLOSE', 'Close File'), ('RECALL', 'Recall Forwarded File'), ('KEEP_IN_FILE', 'Keep in File'), ('EXTERNAL', 'Send to Government/External'), ('ACK_RETURN', 'Acknowledge Return')], max_length=20),
        ),
    ]
