# Generated by Django 4.2.28 on 2026-08-19 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetracking', '0011_alter_fileaction_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemaster',
            name='processing_note',
            field=models.TextField(blank=True, help_text="Current holder's internal processing status/note", null=True),
        ),
        migrations.AlterField(
            model_name='fileaction',
            name='action_type',
            field=models.CharField(choices=[('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('RETURN', 'Return for Clarification'), ('FORWARD', 'Forward'), ('CLOSE', 'Close File'), ('RECALL', 'Recall Forwarded File'), ('KEEP_IN_FILE', 'Keep in File'), ('EXTERNAL', 'Send to Government/External'), ('ACK_RETURN', 'Acknowledge Return'), ('PROCESSING_NOTE', 'Add Processing Note')], max_length=20),
        ),
    ]
